language: node_js
node_js:
  - "14"
dist: xenial
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://104.42.96.156:2376"
    - DOCKER_CERT_PATH="$TRAVIS_BUILD_DIR/azure"
    - DOCKER_MACHINE_NAME="figure2020"
    - COMPOSE_TLS_VERSION=TLSv1_2

script:
  - cd ./server && npm install
  - cd ..
  - docker-compose --file docker-compose.prod.yml build
  - cd ./server && npm test
  - cd ..

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose --file docker-compose.prod.yml up -d --remove-orphans
  on:
    branch: master
