language: node_js
node_js:
  - "8"
dist: xenial  
sudo: required
services:
  - docker

env:
  global:
    - DOCKER_TLS_VERIFY="1"
    - DOCKER_HOST="tcp://13.93.200.96:2376"
    - DOCKER_CERT_PATH="$TRAVIS_BUILD_DIR/azure"
    - DOCKER_MACHINE_NAME="figure2020"

install:
  - cd server && npm install && cd ..
  - cd client && npm install && cd ..
  - npm install

script:
  - cd ./server && npm install
  - cd ..
  - docker-compose --file docker-compose.prod.yml build
  - cd ./server && npm test
  - cd ..

deploy:
  skip_cleanup: true
  provider: script
  script: docker-compose --file docker-compose.prod.yml up -d --remove-orphans
  on:
    branch: master
